/* Table creation DDL */

--DROP TABLE PTCA_CONDITION
CREATE TABLE PTCA_CONDITION(
	COND_ID INTEGER UNIQUE IDENTITY(1,1) NOT NULL,
	CLIENTID INTEGER,
	CONDTYPEID VARCHAR(100),
	ENTERED_DATE DATE DEFAULT GETDATE(),
	PRIMARY KEY (COND_ID)
)

--DROP TABLE PTCA_USERS
CREATE TABLE PTCA_USERS(
	USERID INTEGER NOT NULL	UNIQUE IDENTITY(1,1),
	USERNAME VARCHAR(100) NOT NULL UNIQUE,
	ENC_PASSWORD VARCHAR(50) NOT NULL,
	PRIMARY KEY(USERID)
)

--DROP TABLE PTCA_CLIENTS
CREATE TABLE PTCA_CLIENTS(
	CLIENT_ID INTEGER NOT NULL UNIQUE IDENTITY(1,1),
	USERID INTEGER NOT NULL,
	FIRSTNAME VARCHAR(100) NOT NULL,
	LASTNAME VARCHAR(100) NOT NULL,
	MIDDLENAME VARCHAR(100),
	GENDER CHAR NOT NULL,
	DOB DATE,
	LASTSCHED DATE,
	ISACTIVE BIT NOT NULL DEFAULT 1,
	NOTES VARCHAR(5000),
	IMAGE_PATH VARCHAR(500),
	PRIMARY KEY(CLIENT_ID)
)

--DROP TABLE PTCA_MEASUREMENT_SET
CREATE TABLE PTCA_MEASUREMENT_SET(
	MS_ID INTEGER NOT NULL UNIQUE IDENTITY(1,1),
	CLIENT_ID INTEGER NOT NULL,
	DATE_TAKEN DATE NOT NULL,
	HEIGHTIN INTEGER,
	CL_WEIGHT INTEGER,
	CHEST INTEGER,
	WAIST INTEGER,
	ARM INTEGER,
	HIPS INTEGER,
	THIGH INTEGER,
	BODYFAT INTEGER,
	NOTES VARCHAR(5000),
	PRIMARY KEY(MS_ID)
)


INSERT INTO PTCA_CLIENTS 
VALUES( 1, 'Bill', 'Doe', 'Wilkes', 'M', '11/28/2013', '09/10/2013', 1, 'He loves Ninja', 'C:\Users\nbergez\Pictures\PTCA_Images\ninjaturtles.jpg')

INSERT INTO PTCA_CLIENTS
VALUES( 1, 'Joseph', 'Wild', 'Mandrain', 'M', '05/21/1985', '09/10/2011', 0, 'Hasn''t been here for a while.', 'C:\Users\nbergez\Pictures\PTCA_Images\nophoto.jpg')

INSERT INTO PTCA_CLIENTS
VALUES( 2, 'Bill', 'Doe', 'Wilkes', 'M', '11/28/2013', '09/10/2013', 1, 'He loves Pirate', 'C:\Users\nbergez\Pictures\PTCA_Images\Pirate.jpg')

INSERT INTO PTCA_USERS
VALUES('Ninja', 'password')

INSERT INTO PTCA_MEASUREMENT_SET
VALUES( 1, '05/28/2010',72, 180, 50, 30, 15, 35, 25, 15, 'Extremely cool cat')

INSERT INTO PTCA_MEASUREMENT_SET
VALUES( 2, '12/2/2013',72, 180, 50, 30, 15, 35, 25, 15, 'Extremely cool cat')

INSERT INTO PTCA_MEASUREMENT_SET
VALUES( 3, '12/3/2013',72, 150, 40, 29, 17, 38, 27, 11, 'Extremely cool dog')